# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48d10bf35e172b6d73aa75a9612d798c9b8eaaab1aa3694c1a2839ace5744495e1fb470b3cf7e81b118196b1ff746b90b7b06674822c5b0db79082699439b20f

test:
  secret_key_base: 62ba122fdcc65a738d1a6d8584d394f5a7af0f6c98a30dc01e65ba549e72080b12791d17a4d49e44e970d7837933bae81a933d336e1f1a06ee2039f9c127e49d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
